---
title: "Cases by Health Board."
author: "Michael Kent"
date: "07/12/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
here()
```
Data from COpositive-rate-daily-smoothed.xlsx
Input table cases_by_hb
# Reading in the data
This is rough and ready.  It needs much data manipulation of the spreadsheet then the data for the last few weeks is always poor.

```{r datainput}
# Standardised input - one dataset per spreadsheet/CSV

# New with new names
global_positivity <- read_excel("data/positive-rate-daily-smoothed.xlsx", 
    sheet = "Filter2")
# j_sc_d_cases_by_hb <- read_excel(here("data","cases_by_hb.xlsx"))

sc_d_cases_by_hb <- read_excel("data/S_SCO-UK-Testing-data.xlsx",  sheet = "d_cases_by_hb")


j_global_positivity = janitor::clean_names(global_positivity)
#j_sc_d_cases_by_hb_zoom <- j_global_positivity[-c(1:205), ]
#j_uk_d_28_day_testing_zoom <- j_uk_d_28_day_testing[-c(1:152), ]  #   Data from 1st Agust
names(j_global_positivity)
## TEST EXCELL from raw spreadsheet  
#sc_test_cases_by_hb <- read_excel(here("data","20201222_byHB.xlsx"))

```
```{r}

# # LABELS
# labels_HB_Data <- as_labeller(c(
#                   `nhs_ayrshire_arran`="NHS Ayrshire & Arran",
#                   `nhs_borders`="NHS Borders",
#                   `nhs_dumfries_galloway`="NHS Dumfries & Galloway",
#                   `nhs_fife`="NHS Fife",
#                   `nhs_forth_valley`="NHS Forth Valley",
#                   `nhs_grampian`="NHS Grampian",
#                   `nhs_greater_glasgow_clyde`="NHS Greater Glasgow & Clyde",
#                   `nhs_highland`="NHS Highland",
#                   `nhs_lanarkshire`="NHS Lanarkshire",
#                   `nhs_lothian`="NHS Lothian",
#                   `nhs_orkney`="NHS Orkney",
#                   `nhs_shetland`="NHS Shetland",
#                   `nhs_tayside`="NHS Tayside",
#                   `nhs_western_isles`="NHS Western Isles",
#                   `scotland`="Scotland"
#                   ))
today <- format(Sys.Date(), format="%Y-%m-%d ") 
```

```{r two}
# First data frame is for Sco/UK testing comparison.
df_global_positivity <- data.frame(j_global_positivity) %>%
  select(entity,date,  short_term_positivity_rate) #%>%
#  gather(key = "entity", value = "short_term_positivity_rate",-date)
head(df_global_positivity)
```

```{r}

# First, draw the Sco/UK testing
# Main
# Caption with website
v_caption = paste( "Chart © Thetrue.scot \n","Data Source: Scottish and UK government statistics as published ", pubdate,  sep = "", collapse=NULL)

# Caption - No Website
#v_caption = paste( "Data Source: Scottish and UK government statistics as published ", pubdate,  sep = "", collapse=NULL)

v_title="Global Positivity"
v_xlabel = "Date"
v_ylabel = "New Cases (7 day average)"
v_image_file_name = paste(today, "Global Positivity.jpg", sep = "", collapse=NULL)
v_image_file_name2 = paste(today, "Average new cases by HB.jpg", sep = "", collapse=NULL)
# Set up the default plot configuration.
p <- ggplot(df_global_positivity, aes(x = date, y =short_term_positivity_rate , group = entity)) 
#pset1 <-  geom_line(aes(color = variable),size=0.75 ,labeller = labels_HB_Data)
pset1 <-  geom_line(aes(color = entity),size=0.75 )
pset2 <-  theme_light() 
pset3 <-  labs(x = v_xlabel,
          y = v_ylabel, 
          title = v_title,
          caption = v_caption,
          color = "list")

p + pset1  + pset2  + pset3 + facet_wrap(~ entity, ncol=4, labeller = labels_HB_Data,  as.table = TRUE)
# Plot group chart
ggsave(here("figures", v_image_file_name), dpi = 180, width = 22, height = 6)
#----------------
# p <- ggplot(df_sc_d_cases_by_hb, aes(x = date_notified, y = value)) + 
#   geom_line(aes(color = variable),size=0.75 ) + theme_light() + 
#       labs(x = v_xlabel,
#            y = v_ylabel, 
#           title = v_title,
#           caption = v_caption,
#           color = "")
# p 
#                    # Plot group chart
# ggsave(here("figures", v_image_file_name), dpi = 180, width = 12, height = 6)
# #----------------
# p_facet <- facet_wrap(~ variable, ncol=4, labeller = labels_HB_Data, scales = "free_y", as.table = TRUE)  
# p +  p_facet + theme(legend.position = "none")
# 
# # plot matrix of individual charts.
# ggsave(here("figures", v_image_file_name2 ), dpi = 360, width = 12, height = 6)

```